### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by thiagogsr** [Bidu/home_alone#4]
Setup and deploy to heroku. Add authentication token.

**Comment by renatomenegasso** [comment]
No #5, foi gerada uma versão na qual é possível fazer o deploy no Heroku 👍 

Só faltou mesmo adicionar o `unicorn` e o `Procfile` (apesar de já funcionar com o hack server). De qualquer forma adicionei aqui: https://github.com/Bidu/home_alone/pull/6 

O que acha?

**Comment by thiagogsr** [comment]
Essa issue foi pra o deploy das prs pendentes, por isso mencionei o auth token. Da forma que você fez está beleza 👍 quando for subir o release com prs, adiciono o que for necessário. Tenho algumas idéias e irei aplicar no próximo hackday.

**Comment by renatomenegasso** [comment]
Podemos fechar então?
